version: '3'

services:
  app:
    container_name: car-salon-api
    restart: always
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - MONGODB_URI=mongodb://mongo/car-salon-api1
      - SPRING_DATA_MONGODB_HOST=mongo
    depends_on:
      - mongo


  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: "car-salon-api1"
    volumes:
      - ./mongoVolume:/data/db
